fix for iOS: Render label for collection reference asset
player-ui/player pull request #203
Opened 2023-10-24 23:03 UTC by skodamarthi

### Change Type (required)
Indicate the type of change your pull request is:

- [ ] `patch`
- [ ] `minor`
- [ ] `major`

2023-10-24 23:04 UTC, skodamarthi commented
@hborawski Can you please review?

2023-10-26 16:35 UTC, mercillo commented
you may need to pull in the main branch as your builds are failing

2023-10-27 20:11 UTC, hborawski requested changes

2023-10-27 20:11 UTC, hborawski commented on ios/packages/reference-assets/Sources/SwiftUI/CollectionAsset.swift
> +            model.data.label?.asset?.view.font(.label)
This has a [compilation error](https://app.circleci.com/pipelines/github/player-ui/player/1234/workflows/8e44c482-1e9c-4333-a6a8-955ce643e1f6/jobs/6084) as `CollectionData` has no `label` member. You will need to update the data struct to reflect what needs to be decoded

2024-07-31 22:24 UTC, closed without merging