ios expose constantsController #446
player-ui/player pull request #487
Opened 2024-08-09 14:11 UTC by cehan-Chloe

Issue: https://github.com/player-ui/player/issues/446

Test: 
1. add constants controller tests to playerUITests(unit tests)
2. Use reference-assets plugin TextAsset 
Simulator change(new value "abc" from constants):
![image](https://github.com/user-attachments/assets/301c6b0a-1681-43c2-91bf-f0bd2e0c7c97)

TextAsset code change:
```
struct TextAssetView: View {
    /// The viewModel with decoded data, supplied by `TextAsset`
    @ObservedObject var model: AssetViewModel<TextData>
    @Environment(\.constantsController) var constantsController: ConstantsController?

    @ViewBuilder
    var body: some View {
        VStack {
        if let link = model.data.modifiers?.first(where: { $0.type == "link" })?.metaData?.ref {
            Text(model.data.value.stringValue ?? "").bold().modifier(LinkModifier(link)).accessibility(identifier: model.data.id)
        } else {
            let constantValue: String = constantsController?.getConstants(key: "test", namespace: "test")  ?? "sad"
            Text(constantValue)
        }
        }.onAppear {
            constantsController?.addConstants(data: ["test": "abc"], namespace: "test")
        }
    }
}
```

### Change Type (required)
Indicate the type of change your pull request is:

- [ ] `patch`
- [ ] `minor`
- [ ] `major`

### Does your PR have any documentation updates?
- [ ] Updated docs
- [x] No Update needed
- [ ] Unable to update docs

2024-08-09 16:50 UTC, nancywu1 commented on ios/core/Sources/Types/Core/ConstantsController.swift
> +            return value?.toString() as? T
actually i think we need `value?.toObject()` here because `T` can by `any` maybe add a test where getConstants returns an Int to verify it works?

2024-08-09 18:49 UTC, hborawski commented on ios/core/Sources/Types/Core/ConstantsController.swift
> +    public func addConstants(data: Any, namespace: String) -> Void {
We should add docstrings to all public functions

Xcode can scaffold the docstrings for you if you right click a function and do `Add Documentation`

2024-08-09 19:37 UTC, hborawski requested changes

2024-08-09 19:37 UTC, hborawski commented on ios/core/Tests/HeadlessPlayerTests.swift
> +        XCTAssertEqual(nonExistantNamespace, "undefined")
we probably shouldn't be able to get `undefined` back as a string, in Swift we should coalesce this to `nil`

`JSValue` has a property to indicate whether or not it is `undefined` -> https://developer.apple.com/documentation/javascriptcore/jsvalue/isundefined

2024-08-12 21:51 UTC, cehan-Chloe commented
/canary

2024-08-14 14:58 UTC, nancywu1 approved these changes

2024-08-14 17:09 UTC, merged